---
- name: 'Update package sources'
  hosts: 'all'
  tasks:
    - name: 'Configure Debian-like systems'
      block:
        - name: 'Add Zabbix repo'
          apt:
            deb: "https://repo.zabbix.com/zabbix/5.4/debian/pool/main/z/zabbix-release/zabbix-release_5.4-1+debian{{ ansible_facts['distribution_major_version'] }}_all.deb"
        - name: 'Update APT cache'
          apt:
            update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: 'Configure RedHat-like systems'
      block:
        - name: 'Add Zabbix repo'
          yum:
            name: "https://repo.zabbix.com/zabbix/5.4/rhel/{{ ansible_facts['distribution_major_version'] }}/x86_64/zabbix-release-5.4-1.el{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
            state: 'present'
        - name: 'Update YUM cache'
          yum:
            update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: 'Install git'
      package:
        name: 'git'
        state: 'present'

    - name: 'Install ansible_merge_vars'
      pip:
        name: 'ansible_merge_vars'
        state: 'present'

    - name: 'Clone repo'
      git:
        repo: 'https://github.com/Thulium-Drake/zabbix-templates'
        dest: '/opt/zabbix/templates'

    - name: 'Set up MySQL server'
      import_role:
        name: 'geerlingguy.mysql'
      vars:
        mysql_root_password: 'password'
        mysql_root_password_update: true
        mysql_bind_address: '127.0.0.1'
